// Code generated by scripts/gen_go_client.py from openapi.json. DO NOT EDIT.

package omnigent

import (
	"encoding/json"
	"fmt"
)

// isEvent seals the Event interface over the generated ServerStreamEvent
// variants. Declaring the marker method here — in the same package as the
// generated structs — is what lets a caller type-switch over the stream
// exhaustively without the compiler admitting foreign implementations.
func (BrowserActionRequestEvent) isEvent() {}

func (ClientTaskCancelEvent) isEvent() {}

func (CompactionCompletedEvent) isEvent() {}

func (CompactionFailedEvent) isEvent() {}

func (CompactionInProgressEvent) isEvent() {}

func (ElicitationRequestEvent) isEvent() {}

func (ElicitationResolvedEvent) isEvent() {}

func (ErrorEvent) isEvent() {}

func (InProgressEvent) isEvent() {}

func (IncompleteEvent) isEvent() {}

func (OutputFileDoneEvent) isEvent() {}

func (OutputItemDoneEvent) isEvent() {}

func (OutputTextDeltaEvent) isEvent() {}

func (PolicyDeniedEvent) isEvent() {}

func (QueuedEvent) isEvent() {}

func (ReasoningStartedEvent) isEvent() {}

func (ReasoningSummaryTextDeltaEvent) isEvent() {}

func (ReasoningTextDeltaEvent) isEvent() {}

func (ResponseCancelledEvent) isEvent() {}

func (ResponseCompletedEvent) isEvent() {}

func (ResponseCreatedEvent) isEvent() {}

func (ResponseFailedEvent) isEvent() {}

func (ResponseHeartbeatEvent) isEvent() {}

func (RetryEvent) isEvent() {}

func (SessionAgentChangedEvent) isEvent() {}

func (SessionChangedFilesInvalidatedEvent) isEvent() {}

func (SessionChildSessionUpdatedEvent) isEvent() {}

func (SessionCollaborationModeEvent) isEvent() {}

func (SessionCreatedEvent) isEvent() {}

func (SessionHeartbeatEvent) isEvent() {}

func (SessionInputConsumedEvent) isEvent() {}

func (SessionInterruptedEvent) isEvent() {}

func (SessionMcpStartupEvent) isEvent() {}

func (SessionModelEvent) isEvent() {}

func (SessionModelOptionsEvent) isEvent() {}

func (SessionPresenceEvent) isEvent() {}

func (SessionReasoningEffortEvent) isEvent() {}

func (SessionResourceCreatedEvent) isEvent() {}

func (SessionResourceDeletedEvent) isEvent() {}

func (SessionSandboxStatusEvent) isEvent() {}

func (SessionSkillsEvent) isEvent() {}

func (SessionStatusEvent) isEvent() {}

func (SessionSupersededEvent) isEvent() {}

func (SessionTerminalActivityEvent) isEvent() {}

func (SessionTerminalPendingEvent) isEvent() {}

func (SessionTodosEvent) isEvent() {}

func (SessionUsageEvent) isEvent() {}

func (ToolOutputDeltaEvent) isEvent() {}

func (TurnCancelledEvent) isEvent() {}

func (TurnCompletedEvent) isEvent() {}

func (TurnFailedEvent) isEvent() {}

func (TurnStartedEvent) isEvent() {}

// decodeEvent decodes one SSE frame's JSON payload into the Event variant its
// discriminator ("type") selects. An unrecognized type is not an error: the
// server's event schemas ignore unknown fields by contract, so a client built
// against an older spec surfaces a new event as an UnknownEvent and keeps
// streaming.
func decodeEvent(typ string, data []byte) (Event, error) {
	switch typ {
	case "browser.action_request":
		var ev BrowserActionRequestEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode browser.action_request event: %w", err)
		}
		return ev, nil
	case "response.cancelled":
		var ev ResponseCancelledEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.cancelled event: %w", err)
		}
		return ev, nil
	case "response.client_task.cancel":
		var ev ClientTaskCancelEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.client_task.cancel event: %w", err)
		}
		return ev, nil
	case "response.compaction.completed":
		var ev CompactionCompletedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.compaction.completed event: %w", err)
		}
		return ev, nil
	case "response.compaction.failed":
		var ev CompactionFailedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.compaction.failed event: %w", err)
		}
		return ev, nil
	case "response.compaction.in_progress":
		var ev CompactionInProgressEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.compaction.in_progress event: %w", err)
		}
		return ev, nil
	case "response.completed":
		var ev ResponseCompletedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.completed event: %w", err)
		}
		return ev, nil
	case "response.created":
		var ev ResponseCreatedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.created event: %w", err)
		}
		return ev, nil
	case "response.elicitation_request":
		var ev ElicitationRequestEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.elicitation_request event: %w", err)
		}
		return ev, nil
	case "response.elicitation_resolved":
		var ev ElicitationResolvedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.elicitation_resolved event: %w", err)
		}
		return ev, nil
	case "response.error":
		var ev ErrorEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.error event: %w", err)
		}
		return ev, nil
	case "response.failed":
		var ev ResponseFailedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.failed event: %w", err)
		}
		return ev, nil
	case "response.function_call_output.delta":
		var ev ToolOutputDeltaEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.function_call_output.delta event: %w", err)
		}
		return ev, nil
	case "response.heartbeat":
		var ev ResponseHeartbeatEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.heartbeat event: %w", err)
		}
		return ev, nil
	case "response.in_progress":
		var ev InProgressEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.in_progress event: %w", err)
		}
		return ev, nil
	case "response.incomplete":
		var ev IncompleteEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.incomplete event: %w", err)
		}
		return ev, nil
	case "response.output_file.done":
		var ev OutputFileDoneEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.output_file.done event: %w", err)
		}
		return ev, nil
	case "response.output_item.done":
		var ev OutputItemDoneEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.output_item.done event: %w", err)
		}
		return ev, nil
	case "response.output_text.delta":
		var ev OutputTextDeltaEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.output_text.delta event: %w", err)
		}
		return ev, nil
	case "response.policy_denied":
		var ev PolicyDeniedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.policy_denied event: %w", err)
		}
		return ev, nil
	case "response.queued":
		var ev QueuedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.queued event: %w", err)
		}
		return ev, nil
	case "response.reasoning.started":
		var ev ReasoningStartedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.reasoning.started event: %w", err)
		}
		return ev, nil
	case "response.reasoning_summary_text.delta":
		var ev ReasoningSummaryTextDeltaEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.reasoning_summary_text.delta event: %w", err)
		}
		return ev, nil
	case "response.reasoning_text.delta":
		var ev ReasoningTextDeltaEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.reasoning_text.delta event: %w", err)
		}
		return ev, nil
	case "response.retry":
		var ev RetryEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode response.retry event: %w", err)
		}
		return ev, nil
	case "session.agent_changed":
		var ev SessionAgentChangedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.agent_changed event: %w", err)
		}
		return ev, nil
	case "session.changed_files.invalidated":
		var ev SessionChangedFilesInvalidatedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.changed_files.invalidated event: %w", err)
		}
		return ev, nil
	case "session.child_session.updated":
		var ev SessionChildSessionUpdatedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.child_session.updated event: %w", err)
		}
		return ev, nil
	case "session.collaboration_mode":
		var ev SessionCollaborationModeEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.collaboration_mode event: %w", err)
		}
		return ev, nil
	case "session.created":
		var ev SessionCreatedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.created event: %w", err)
		}
		return ev, nil
	case "session.heartbeat":
		var ev SessionHeartbeatEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.heartbeat event: %w", err)
		}
		return ev, nil
	case "session.input.consumed":
		var ev SessionInputConsumedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.input.consumed event: %w", err)
		}
		return ev, nil
	case "session.interrupted":
		var ev SessionInterruptedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.interrupted event: %w", err)
		}
		return ev, nil
	case "session.mcp_startup":
		var ev SessionMcpStartupEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.mcp_startup event: %w", err)
		}
		return ev, nil
	case "session.model":
		var ev SessionModelEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.model event: %w", err)
		}
		return ev, nil
	case "session.model_options":
		var ev SessionModelOptionsEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.model_options event: %w", err)
		}
		return ev, nil
	case "session.presence":
		var ev SessionPresenceEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.presence event: %w", err)
		}
		return ev, nil
	case "session.reasoning_effort":
		var ev SessionReasoningEffortEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.reasoning_effort event: %w", err)
		}
		return ev, nil
	case "session.resource.created":
		var ev SessionResourceCreatedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.resource.created event: %w", err)
		}
		return ev, nil
	case "session.resource.deleted":
		var ev SessionResourceDeletedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.resource.deleted event: %w", err)
		}
		return ev, nil
	case "session.sandbox_status":
		var ev SessionSandboxStatusEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.sandbox_status event: %w", err)
		}
		return ev, nil
	case "session.skills":
		var ev SessionSkillsEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.skills event: %w", err)
		}
		return ev, nil
	case "session.status":
		var ev SessionStatusEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.status event: %w", err)
		}
		return ev, nil
	case "session.superseded":
		var ev SessionSupersededEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.superseded event: %w", err)
		}
		return ev, nil
	case "session.terminal.activity":
		var ev SessionTerminalActivityEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.terminal.activity event: %w", err)
		}
		return ev, nil
	case "session.terminal_pending":
		var ev SessionTerminalPendingEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.terminal_pending event: %w", err)
		}
		return ev, nil
	case "session.todos":
		var ev SessionTodosEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.todos event: %w", err)
		}
		return ev, nil
	case "session.usage":
		var ev SessionUsageEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode session.usage event: %w", err)
		}
		return ev, nil
	case "turn.cancelled":
		var ev TurnCancelledEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode turn.cancelled event: %w", err)
		}
		return ev, nil
	case "turn.completed":
		var ev TurnCompletedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode turn.completed event: %w", err)
		}
		return ev, nil
	case "turn.failed":
		var ev TurnFailedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode turn.failed event: %w", err)
		}
		return ev, nil
	case "turn.started":
		var ev TurnStartedEvent
		if err := json.Unmarshal(data, &ev); err != nil {
			return nil, fmt.Errorf("decode turn.started event: %w", err)
		}
		return ev, nil
	default:
		return UnknownEvent{Type: typ, Raw: append([]byte(nil), data...)}, nil
	}
}
