"""Generate the Go SDK's bindings from the checked-in ``openapi.json``.

``openapi.json`` is the source of truth external SDK tooling reads (see
``tests/server/test_openapi_drift.py``, which pins it byte-for-byte to the live
FastAPI app). This script turns it into the two generated files the Go module at
``sdks/go-client`` ships:

- ``models.gen.go`` — the Go types for the schemas this SDK's surface needs,
  emitted by ``oapi-codegen`` (models only: no client, no server, no spec blob).
- ``events.gen.go`` — the sealed ``Event`` interface's membership and the
  ``type``-string dispatch for the 52-member ``ServerStreamEvent`` union,
  derived from that schema's ``discriminator.mapping``.

Generated code is checked in — ``go get`` fetches a module as source with no
build step, so an ungenerated module simply does not compile for consumers —
and this script is the one blessed way to regenerate it. Run it whenever
``openapi.json`` changes and commit the result.

These transformations happen, in this order, in a temp dir that is never
committed:

1. :func:`_prune` narrows the document to the schemas the SDK's exported API is
   built from — the ``$ref`` closure of :data:`_HANDWRITTEN_ROOTS` plus every
   ``ServerStreamEvent`` variant — and empties ``paths``. Generating the whole
   document instead would export 262 types nobody chose, including 46 named
   after FastAPI's path-mangled operationIds. Narrowing cannot hide a spec
   change: the roots are looked up by name (absent ones fail the build), the
   event roots are read from the union's own discriminator, and the closure
   follows ``$ref`` — so a schema gaining a field, or a reference to a new
   schema, still moves the generated bytes and trips ``--check``.
2. :func:`_downgrade` rewrites the 3.2.0 / JSON-Schema-2020-12 document into the
   OAS 3.0 dialect ``oapi-codegen``'s loader (kin-openapi) models.
   :func:`_assert_supported` then checks every surviving schema keyword against
   an allowlist of keywords the downgrade handles and fails closed on anything
   else, so a new JSON-Schema construct stops the build instead of silently
   degrading a Go type. The allowlist constrains keywords, not values: a new
   ``format``, or a genuinely heterogeneous ``anyOf``, still generates whatever
   ``oapi-codegen`` makes of it.
3. :func:`_rename_event_schemas` namespaces any event whose trailing name is
   published under two ``type`` prefixes, so ``response.heartbeat`` cannot
   answer to the bare Go name a reader reaching for ``session.heartbeat`` would
   type.
4. :func:`_sanitize_descriptions` redacts the server's own internals — private
   attribute names, ``.py`` source references, absolute home directories — out
   of the descriptions that become published Go doc comments, and fails closed
   on a variant of one of those three shapes it was not taught. It recognises
   references by shape, so what it does *not* cover is a dotted lowercase module
   path: ``omnigent.runtime.pending_inputs`` is the same shape as the
   wire-visible label key ``omnigent.codex_native.collaboration_mode``, and the
   two cannot be told apart without knowing which names the server publishes.
   Five such paths survive in ten doc comments; see the package README.
5. :func:`_annotate_wire_types` appends each event's wire ``type`` to its doc
   verbatim. It runs *after* the redaction so that what it appends is not
   subject to it: a wire ``type`` is the contract this package documents, and no
   part of it should ever read as an internal reference.
6. :func:`_skip_optional_collection_pointers` marks every array- and map-valued
   schema so an absent one is a nil slice or map rather than ``*[]T`` /
   ``*map[K]V``. Pointer-to-collection is not a Go idiom, and removing it after
   a v1 tag would be a breaking change.
7. :func:`_detach_package_comment` strips the package doc ``oapi-codegen``
   attaches to its header, because the package doc belongs in ``doc.go`` and two
   of them render concatenated.

Pass ``--check`` to verify the committed bindings are up to date without
writing: it regenerates into a temp dir, compares, and exits non-zero if
``openapi.json`` was edited without regenerating. The ``go-client-fresh``
pre-commit hook runs it in this mode. ``--check`` fails closed when
``oapi-codegen`` is absent; see :func:`_check`.

Usage::

    python scripts/gen_go_client.py            # (re)generate in place
    python scripts/gen_go_client.py --check    # verify freshness (CI / hook)
"""

from __future__ import annotations

import argparse
import filecmp
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

# Repo root (this file lives in ``scripts/``).
_REPO_ROOT = Path(__file__).resolve().parent.parent
_SPEC = Path("openapi.json")
_GO_DIR = Path("sdks/go-client")
_CONFIG = _GO_DIR / "oapi-codegen.yaml"
_MODELS = _GO_DIR / "models.gen.go"
_EVENTS = _GO_DIR / "events.gen.go"
_OUTPUTS = (_MODELS, _EVENTS)

# The union whose discriminator drives events.gen.go, and whose members are the
# bulk of the generated surface. The union type itself is deliberately NOT
# generated: Event already models a decoded frame, so its generated form would
# be a second, undocumented public representation of the same thing — 52
# accessor methods over a json.RawMessage that nothing in this package returns.
_UNION = "ServerStreamEvent"

# Schemas the hand-written code names directly. Everything else in
# models.gen.go is here because one of these, or a ServerStreamEvent variant,
# refers to it.
_HANDWRITTEN_ROOTS = (
    # Snapshot returned by CreateSession and GetSession.
    "SessionResponse",
    # Body of DeleteSession's response.
    "ConversationDeleted",
    # SessionCreateRequest.Git, on the hand-written create body.
    "SessionGitOptions",
    # Element type of APIError.ValidationErrors.
    "ValidationError",
    # Element type of the agents listing, `Page[AgentObject]`, from
    # GET /v1/agents. The route's declared response is the shared PaginatedList,
    # whose `data` is untyped because it is reused across routes that return
    # different things; this route builds its page out of AgentObject, so the SDK
    # types it as that rather than inheriting an `[]any` the caller would have to
    # re-decode.
    "AgentObject",
    # Element type of the sessions listing, `Page[SessionListItem]`, from
    # GET /v1/sessions.
    "SessionListItem",
)

_REGEN_HINT = "  python scripts/gen_go_client.py"

# Opt-out for a contributor with no Go toolchain; ignored in CI. See _check.
_SKIP_ENV = "OMNIGENT_SKIP_GO_CLIENT_CHECK"

_OAPI_CODEGEN_INSTALL = (
    "  go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.6.0"
)


# ── narrowing ────────────────────────────────────────────────────────


def _referenced(node: Any, found: set[str]) -> None:
    """Collect the component-schema names ``$ref``-ed anywhere under node."""
    if isinstance(node, list):
        for item in node:
            _referenced(item, found)
        return
    if not isinstance(node, dict):
        return
    for key, value in node.items():
        if key == "$ref" and isinstance(value, str):
            found.add(value.rsplit("/", 1)[-1])
        else:
            _referenced(value, found)


def _closure(schemas: dict[str, Any], roots: set[str]) -> set[str]:
    """Return roots plus every component schema reachable from them by ``$ref``."""
    missing = sorted(name for name in roots if name not in schemas)
    if missing:
        raise SystemExit(
            "openapi.json no longer defines schemas the Go SDK is built from: "
            f"{', '.join(missing)}\n"
            "The SDK's hand-written code names them; reconcile it before regenerating."
        )
    reached: set[str] = set()
    pending = list(roots)
    while pending:
        name = pending.pop()
        if name in reached:
            continue
        reached.add(name)
        schema = schemas.get(name)
        if schema is None:
            raise SystemExit(
                f"openapi.json references a component schema it does not define: {name}"
            )
        found: set[str] = set()
        _referenced(schema, found)
        pending.extend(found - reached)
    return reached


def _prune(spec: dict[str, Any], keep: set[str]) -> dict[str, Any]:
    """Narrow spec to the schemas in keep, with no operations left to generate."""
    schemas = spec["components"]["schemas"]
    spec["components"]["schemas"] = {
        name: schema for name, schema in schemas.items() if name in keep
    }
    # Operations are what produce the `*Params` and
    # `*V1SessionsSessionID...JSONRequestBody` types. The SDK's request path is
    # hand-written, so none of them is API anyone asked for.
    spec["paths"] = {}
    return spec


# ── 3.2 → 3.0 downgrade ──────────────────────────────────────────────


def _downgrade_node(node: Any) -> None:
    """Rewrite one node's 3.1-only constructs in place, then recurse."""
    if isinstance(node, list):
        for item in node:
            _downgrade_node(item)
        return
    if not isinstance(node, dict):
        return

    # ``anyOf``/``oneOf`` containing ``{"type": "null"}`` is how JSON Schema
    # 2020-12 (and therefore FastAPI) spells an optional field. 3.0 spells it
    # ``nullable: true`` on the member itself, so drop the null branch and
    # inline the sole survivor; a genuine multi-member union keeps its keyword.
    for keyword in ("anyOf", "oneOf"):
        members = node.get(keyword)
        if not isinstance(members, list):
            continue
        if not any(isinstance(m, dict) and m.get("type") == "null" for m in members):
            continue
        rest = [m for m in members if not (isinstance(m, dict) and m.get("type") == "null")]
        del node[keyword]
        node["nullable"] = True
        if len(rest) == 1 and isinstance(rest[0], dict):
            for key, value in rest[0].items():
                node.setdefault(key, value)
        elif rest:
            node[keyword] = rest

    # 3.1 makes the exclusive bounds numeric; 3.0 pairs a bound with a flag.
    for bound, inclusive in (("exclusiveMinimum", "minimum"), ("exclusiveMaximum", "maximum")):
        value = node.get(bound)
        if isinstance(value, bool) or not isinstance(value, int | float):
            continue
        node[inclusive] = value
        node[bound] = True

    # ``const: X`` is a single-valued ``enum`` in 3.0. FastAPI emits it for
    # every discriminated event's ``type`` literal.
    if "const" in node:
        node["enum"] = [node.pop("const")]

    # OAS 3.2's per-item schema for a streaming media type. Only reachable from
    # an operation today, so _prune usually removes it first; kept because a
    # component schema is free to carry one.
    if "itemSchema" in node:
        node["schema"] = node.pop("itemSchema")

    for value in list(node.values()):
        _downgrade_node(value)


def _downgrade(spec: dict[str, Any]) -> dict[str, Any]:
    """Return a 3.0.3 rendering of spec that kin-openapi can load."""
    _downgrade_node(spec)
    spec["openapi"] = "3.0.3"
    return spec


# ── fail-closed keyword allowlist ────────────────────────────────────

# Keywords whose value is one sub-schema. ``additionalProperties`` may instead
# be a boolean, which 3.0 allows verbatim.
_SUBSCHEMA_VALUE = ("not", "items", "additionalProperties")

# Keywords whose value maps names to sub-schemas.
_SUBSCHEMA_MAP = ("properties",)

# Keywords whose value is a list of sub-schemas.
_SUBSCHEMA_LIST = ("allOf", "anyOf", "oneOf")

# Keywords that carry no sub-schema and cannot degrade a generated Go type:
# either kin-openapi honours them, or it ignores them and the emitted type is
# the same either way.
_ANNOTATIONS = frozenset(
    {
        "$ref",
        "default",
        "deprecated",
        "description",
        "discriminator",
        "enum",
        "example",
        "examples",
        "exclusiveMaximum",
        "exclusiveMinimum",
        "externalDocs",
        "format",
        "maxItems",
        "maxLength",
        "maxProperties",
        "maximum",
        "minItems",
        "minLength",
        "minProperties",
        "minimum",
        "multipleOf",
        "nullable",
        "pattern",
        "readOnly",
        "required",
        "title",
        "type",
        "uniqueItems",
        "writeOnly",
        "xml",
    }
)

_SUPPORTED = (
    frozenset(_SUBSCHEMA_VALUE)
    | frozenset(_SUBSCHEMA_MAP)
    | frozenset(_SUBSCHEMA_LIST)
    | _ANNOTATIONS
)

# 3.0 types. A list-valued or ``"null"`` type is 2020-12 only.
_TYPES = frozenset({"array", "boolean", "integer", "number", "object", "string"})


def _unsupported(node: Any, path: str, found: list[str]) -> None:
    """Collect schema keywords the downgrade does not handle, under path."""
    if isinstance(node, bool):
        # A boolean schema (2020-12) has no 3.0 spelling.
        found.append(f"{path}: boolean schema")
        return
    if not isinstance(node, dict):
        found.append(f"{path}: not a schema object")
        return

    for key, value in node.items():
        if key not in _SUPPORTED:
            found.append(f"{path}: {key}")
            continue
        if key == "type" and not (isinstance(value, str) and value in _TYPES):
            # A list-valued or "null" type is 2020-12 only; anything else is
            # not a type at all.
            found.append(f"{path}: type: {json.dumps(value)}")
        elif key in _SUBSCHEMA_VALUE:
            if key == "additionalProperties" and isinstance(value, bool):
                continue
            if key == "items" and isinstance(value, list):
                # 2020-12's tuple form; 3.0 takes exactly one schema.
                found.append(f"{path}: items: tuple form")
                continue
            _unsupported(value, f"{path}/{key}", found)
        elif key in _SUBSCHEMA_MAP:
            if not isinstance(value, dict):
                found.append(f"{path}: {key}: not a map of schemas")
                continue
            for name, sub in value.items():
                _unsupported(sub, f"{path}/{key}/{name}", found)
        elif key in _SUBSCHEMA_LIST:
            if not isinstance(value, list):
                found.append(f"{path}: {key}: not a list of schemas")
                continue
            for index, sub in enumerate(value):
                _unsupported(sub, f"{path}/{key}[{index}]", found)


def _assert_supported(spec: dict[str, Any]) -> None:
    """Fail closed when a schema the SDK generates uses an unhandled keyword.

    The check is an allowlist, not a list of known-bad keywords: anything the
    downgrade has not been taught is a build failure, so a spec change cannot
    quietly turn a Go type into ``interface{}``. It covers exactly the schemas
    that become Go types — the pruned ``components.schemas`` — because the rest
    of the document is out of scope by construction.
    """
    found: list[str] = []
    for name, schema in spec["components"]["schemas"].items():
        _unsupported(schema, name, found)
    if not found:
        return
    listed = "\n".join(f"  {item}" for item in found[:20])
    more = "" if len(found) <= 20 else f"\n  ... and {len(found) - 20} more"
    raise SystemExit(
        "openapi.json uses JSON-Schema constructs the 3.0 downgrade does not\n"
        "handle. Generating anyway could silently degrade a Go type. Teach\n"
        f"scripts/gen_go_client.py these constructs:\n{listed}{more}"
    )


# ── event type names ─────────────────────────────────────────────────


def _camel(fragment: str) -> str:
    """Render a wire-``type`` fragment as a Go identifier fragment."""
    return "".join(part.capitalize() for part in re.split(r"[._-]+", fragment) if part)


def _event_go_names(variants: list[tuple[str, str]]) -> dict[str, str]:
    """Map each wire ``type`` to the Go type name the SDK will publish for it.

    A variant keeps openapi.json's schema name unless a second ``type`` prefix
    publishes an event with the same trailing name. Five pairs do:
    ``response.heartbeat``/``session.heartbeat``,
    ``response.created``/``session.created``, and ``response.*``/``turn.*`` for
    the three terminal states. There the bare name is a trap rather than a
    convenience — the type a reader reaches for is whichever of the two the spec
    happened to name without a prefix, and for the heartbeat that is the wrong
    one. Every member of such a group is therefore namespaced from its own wire
    ``type``, so the wire ``type`` is recoverable from the Go name and neither
    member can be picked by accident.

    The rule is collision-driven rather than a list, so a new colliding variant
    is namespaced with no edit here.
    """
    tails: dict[str, list[str]] = {}
    for wire, _ in variants:
        namespace, _, rest = wire.partition(".")
        tails.setdefault(_camel(rest) + "Event", []).append(namespace)
    names: dict[str, str] = {}
    for wire, schema in variants:
        namespace, _, rest = wire.partition(".")
        tail = _camel(rest) + "Event"
        names[wire] = _camel(namespace) + tail if len(tails[tail]) > 1 else schema
    return names


def _rewrite_refs(node: Any, renames: dict[str, str]) -> None:
    """Point every ``$ref`` under node at its schema's new name."""
    if isinstance(node, list):
        for item in node:
            _rewrite_refs(item, renames)
        return
    if not isinstance(node, dict):
        return
    for key, value in node.items():
        if key == "$ref" and isinstance(value, str):
            prefix, _, name = value.rpartition("/")
            if name in renames:
                node[key] = f"{prefix}/{renames[name]}"
        else:
            _rewrite_refs(value, renames)


def _rename_event_schemas(
    spec: dict[str, Any], variants: list[tuple[str, str]]
) -> list[tuple[str, str]]:
    """Rename the colliding event schemas in place; return the new variant list.

    The component-schema *key* is renamed rather than only the Go type name
    (``x-go-name``), because oapi-codegen derives a schema's nested types from
    the key: overriding just the type name would leave the single-valued
    ``type`` enum still called ``HeartbeatEventType``.
    """
    schemas = spec["components"]["schemas"]
    go_names = _event_go_names(variants)
    renames = {schema: go_names[wire] for wire, schema in variants if go_names[wire] != schema}
    taken = set(schemas) - set(renames)
    clashes = sorted(new for new in renames.values() if new in taken)
    if clashes:
        raise SystemExit(
            "disambiguating the event names would collide with schemas openapi.json\n"
            f"already defines: {', '.join(clashes)}\n"
            "Reconcile scripts/gen_go_client.py's naming rule with the spec."
        )
    for old, new in renames.items():
        schemas[new] = schemas.pop(old)
    _rewrite_refs(spec, renames)
    return [(wire, go_names[wire]) for wire, _ in variants]


def _annotate_wire_types(spec: dict[str, Any], variants: list[tuple[str, str]]) -> None:
    """State each event's wire ``type`` verbatim in its generated doc comment.

    The Go name is derived from the wire ``type`` but is not the wire ``type``,
    and the discriminator is what a caller reads off a captured frame, so the
    doc says it literally rather than leaving it to be inferred from the name.
    """
    schemas = spec["components"]["schemas"]
    for wire, go_type in variants:
        schema = schemas[go_type]
        note = f'Wire type: "{wire}".'
        existing = schema.get("description", "").rstrip()
        schema["description"] = f"{existing}\n\n{note}" if existing else note


# ── description sanitising ───────────────────────────────────────────

# A reference to the server's own source. Three shapes appear: a backticked path
# or filename carrying a ``.py`` suffix (with or without a line range or a
# trailing symbol), a backticked token containing a private ``_name``, and a
# bare private ``_name``. A private name is recognised only where the underscore
# does not follow an alphanumeric, so ordinary wire fields like `last_event_seq`
# and label keys like `omnigent.codex_native.collaboration_mode` are not
# mistaken for internals.
_INTERNAL_TOKEN = (
    r"`[^`\n]*(?:\.py|(?<![A-Za-z0-9])_[A-Za-z])[^`\n]*`"
    r"|[\w./-]*\w\.py\b(?::[\w.-]+)?"
    r"|(?<![A-Za-z0-9_`])_[A-Za-z]\w*(?:\(\))?"
)

# One or more references as prose joins them, so "`_X` in `y.py`" is one run.
# The joiners are whole words: "workflow" is not a run of "w" and "kflow".
_JOINER = r"(?:\s*,\s*|\s+(?:and|or|in|at|of)\s+)"
_INTERNAL_RUN = rf"(?:{_INTERNAL_TOKEN})(?:{_JOINER}(?:{_INTERNAL_TOKEN}))*"

# The joiners that enumerate two places rather than locating one; see
# :func:`_sanitize_sentence` rule 3.
_ENUMERATING_JOINER_RE = re.compile(r",|\band\b|\bor\b")

# An absolute path under a developer's home directory. openapi.json uses real
# ones as examples; published Go docs must not name somebody's laptop.
_HOME_PATH = r"(?:/Users|/home)/[A-Za-z0-9._-]+(?:/[^\s\"'`)]*)*|/root(?:/[^\s\"'`)]*)*"

_INTERNAL_RE = re.compile(_INTERNAL_TOKEN)
_INTERNAL_RUN_RE = re.compile(_INTERNAL_RUN)
_HOME_PATH_RE = re.compile(_HOME_PATH)
_LEAK_RE = re.compile(rf"{_INTERNAL_TOKEN}|{_HOME_PATH}")

# What a redacted reference becomes. Deliberately not a source path: the point
# is that the Go docs describe the wire contract, not where it is implemented.
# Which of the two reads correctly depends on the slot the reference sat in —
# descriptions cite a source file as a place ("emitted by ...") and a private
# attribute as a thing ("the server's ...") — so the determiner before it picks.
_REDACTED_PLACE = "the server"
_REDACTED_THING = "internal state"

_DETERMINER_RE = re.compile(r"(?:'s|its own|in-memory|the|a|an|their)[ \t\n]+$")

# A neutral stand-in for an example path that named a real home directory.
_PLACEHOLDER_PATH = "/path/to/workspace"

# A parenthetical that is nothing but a pointer at the source, optionally led in.
_POINTER_PARENS_RE = re.compile(rf"\s*\((?:see |the value of )?{_INTERNAL_RUN}\)")

# A trailing "— see <source>" pointer inside a parenthetical that also carries
# prose worth keeping.
_TRAILING_SEE_RE = re.compile(rf"\s*[—–-]+\s*see\s+{_INTERNAL_RUN}\s*(?=\))")

# Sentence boundaries, keeping the original whitespace so a description's own
# hard wrapping survives the surgery.
_SENTENCE_RE = re.compile(r"(?<=[.:])(\s+)")

# Whitespace stranded before punctuation once a parenthetical is removed.
_STRANDED_RE = re.compile(r"[ \t\n]+([,.;:])")


def _sanitize_sentence(sentence: str) -> str | None:
    """Return sentence with source references redacted, or None to drop it.

    Four rules, in order:

    1. A sentence whose whole job is to point at an emit site ("Wire shape
       matches ...") goes.
    2. A sentence naming two separate places goes: redacting both would read as
       "the server's implementation ... and the server's implementation ...".
    3. A sentence naming several places in one breath ("`a.py` and `b.py`") goes
       for the same reason, and because a singular redaction would disagree with
       its plural verb.
    4. Anything else keeps its prose and loses only the reference.
    """
    if not _INTERNAL_RE.search(sentence):
        return sentence
    if sentence.lstrip().startswith("Wire shape"):
        return None
    runs = _INTERNAL_RUN_RE.findall(sentence)
    if len(runs) > 1:
        return None
    run = _INTERNAL_RUN_RE.search(sentence)
    assert run is not None  # _INTERNAL_RE matched, so a run does too.
    if _ENUMERATING_JOINER_RE.search(run.group(0)):
        return None
    head, tail = sentence[: run.start()], sentence[run.end() :]
    replacement = _REDACTED_THING if _DETERMINER_RE.search(head) else _REDACTED_PLACE
    return head + replacement + tail


def _sanitize_description(text: str) -> str:
    """Redact the server's internals out of one description."""
    text = _HOME_PATH_RE.sub(_PLACEHOLDER_PATH, text)
    text = _POINTER_PARENS_RE.sub("", text)
    text = _TRAILING_SEE_RE.sub("", text)
    text = _STRANDED_RE.sub(r"\1", text)

    paragraphs: list[str] = []
    for paragraph in re.split(r"\n[ \t]*\n", text):
        parts = _SENTENCE_RE.split(paragraph)
        # split() alternates sentence, separator, sentence, ...
        kept: list[str] = []
        for index in range(0, len(parts), 2):
            sentence = _sanitize_sentence(parts[index])
            if sentence is None or not sentence.strip():
                continue
            if kept:
                kept.append(parts[index - 1])
            kept.append(sentence)
        joined = "".join(kept).strip()
        if joined:
            paragraphs.append(joined)
    return "\n\n".join(paragraphs)


def _walk_descriptions(node: Any, apply: Any) -> None:
    """Rewrite every ``description`` under node through apply."""
    if isinstance(node, list):
        for item in node:
            _walk_descriptions(item, apply)
        return
    if not isinstance(node, dict):
        return
    for key, value in list(node.items()):
        if key == "description" and isinstance(value, str):
            node[key] = apply(value)
        else:
            _walk_descriptions(value, apply)


def _sanitize_descriptions(spec: dict[str, Any]) -> None:
    """Strip the server's internals out of every published doc comment.

    openapi.json's descriptions are written for the people who maintain the
    server, so they cite emit sites, private attribute names and — in four
    example paths — a real home directory. oapi-codegen copies them verbatim
    into Go doc comments, which pkg.go.dev then publishes. This rewrites them
    into statements about the wire contract, and then fails closed: a reference
    shape it was not taught stops the build rather than reaching the docs.
    """
    _walk_descriptions(spec, _sanitize_description)
    found: list[str] = []
    for name, schema in spec["components"]["schemas"].items():
        _walk_descriptions(
            schema,
            lambda text, name=name: (
                found.extend(f"  {name}: {leak}" for leak in _LEAK_RE.findall(text)) or text
            ),
        )
    if found:
        listed = "\n".join(found[:20])
        more = "" if len(found) <= 20 else f"\n  ... and {len(found) - 20} more"
        raise SystemExit(
            "openapi.json describes the Go SDK's types with references to the server's\n"
            "own source that the sanitiser could not redact. Publishing them would put\n"
            "them on pkg.go.dev. Teach scripts/gen_go_client.py these shapes:\n"
            f"{listed}{more}"
        )


# ── nil-instead-of-pointer for collections ───────────────────────────

# oapi-codegen's per-schema opt-out of the optional-field pointer.
_SKIP_OPTIONAL_POINTER = "x-go-type-skip-optional-pointer"


def _skip_optional_collection_pointers(node: Any) -> None:
    """Mark array- and map-valued schemas so an absent one is nil, not a pointer.

    ``*[]T`` and ``*map[K]V`` are not Go: nil already expresses absence, so the
    pointer adds a second empty state and a dereference to every read — on
    ``SessionResponse.Items``, the field callers touch most. Doing it here rather
    than by hand keeps it done: the next regeneration cannot bring the pointers
    back.

    A struct-valued schema keeps its pointer, which is idiomatic and is how a
    caller distinguishes an absent object from a zeroed one.
    """
    if isinstance(node, list):
        for item in node:
            _skip_optional_collection_pointers(item)
        return
    if not isinstance(node, dict):
        return
    kind = node.get("type")
    # An object with no declared properties generates map[string]T, whether its
    # values are typed by additionalProperties or left as interface{}.
    if kind == "array" or (kind == "object" and "properties" not in node):
        node[_SKIP_OPTIONAL_POINTER] = True
    for value in node.values():
        _skip_optional_collection_pointers(value)


# ── generation ───────────────────────────────────────────────────────


def _run_oapi_codegen(spec_path: Path, out_path: Path) -> None:
    """Emit models for spec_path into out_path via the committed config."""
    cmd = [
        "oapi-codegen",
        "-config",
        str(_REPO_ROOT / _CONFIG),
        "-o",
        str(out_path),
        str(spec_path),
    ]
    try:
        subprocess.run(cmd, check=True, cwd=_REPO_ROOT)
    except FileNotFoundError:
        raise SystemExit(
            f"oapi-codegen not found. Install the pinned version first:\n{_OAPI_CODEGEN_INSTALL}"
        ) from None


def _detach_package_comment(source: str) -> str:
    """Return source with oapi-codegen's package doc removed.

    oapi-codegen opens its output with a "Package omnigent provides primitives
    ..." line attached to the ``package`` clause, which makes it a second
    package doc comment: godoc renders it appended to doc.go's. Keep only the
    ``Code generated`` line — its version stamp is what makes a generator bump
    visible in review — and separate it from the clause with a blank line so it
    documents nothing.
    """
    lines = source.split("\n")
    try:
        clause = next(i for i, line in enumerate(lines) if line.startswith("package "))
    except StopIteration:
        raise SystemExit(
            "oapi-codegen's output has no `package` clause; scripts/gen_go_client.py\n"
            "cannot rewrite its header."
        ) from None
    generated = [line for line in lines[:clause] if line.startswith("// Code generated")]
    if len(generated) != 1:
        raise SystemExit(
            "oapi-codegen's output no longer opens with exactly one `// Code generated`\n"
            f"line (found {len(generated)}). Teach scripts/gen_go_client.py its new header."
        )
    note = "// Regenerate with scripts/gen_go_client.py. The package doc lives in doc.go."
    return "\n".join([*generated, note, "", *lines[clause:]])


def _event_variants(spec: dict[str, Any]) -> list[tuple[str, str]]:
    """Return the union's (wire ``type``, Go type name) pairs, sorted by wire type."""
    union = spec["components"]["schemas"].get(_UNION)
    if union is None:
        raise SystemExit(
            f"openapi.json no longer defines {_UNION}; the Go SDK's event dispatch\n"
            "is derived from it."
        )
    mapping = union.get("discriminator", {}).get("mapping")
    if not mapping:
        raise SystemExit(
            f"{_UNION} lost its discriminator mapping; cannot derive the Go event dispatch."
        )
    return sorted((wire, ref.rsplit("/", 1)[-1]) for wire, ref in mapping.items())


def _render_events(variants: list[tuple[str, str]]) -> str:
    """Render events.gen.go: the sealed-interface membership plus dispatch."""
    lines = [
        "// Code generated by scripts/gen_go_client.py from openapi.json. DO NOT EDIT.",
        "",
        "package omnigent",
        "",
        "import (",
        '\t"encoding/json"',
        '\t"fmt"',
        ")",
        "",
        "// isEvent seals the Event interface over the generated ServerStreamEvent",
        "// variants. Declaring the marker method here — in the same package as the",
        "// generated structs — is what lets a caller type-switch over the stream",
        "// exhaustively without the compiler admitting foreign implementations.",
    ]
    for go_type in sorted({go for _, go in variants}):
        # gofmt separates consecutive top-level declarations with a blank line.
        lines += [f"func ({go_type}) isEvent() {{}}", ""]
    lines += [
        "// decodeEvent decodes one SSE frame's JSON payload into the Event variant its",
        '// discriminator ("type") selects. An unrecognized type is not an error: the',
        "// server's event schemas ignore unknown fields by contract, so a client built",
        "// against an older spec surfaces a new event as an UnknownEvent and keeps",
        "// streaming.",
        "func decodeEvent(typ string, data []byte) (Event, error) {",
        "\tswitch typ {",
    ]
    for wire, go_type in variants:
        lines += [
            f"\tcase {json.dumps(wire)}:",
            f"\t\tvar ev {go_type}",
            "\t\tif err := json.Unmarshal(data, &ev); err != nil {",
            f"\t\t\treturn nil, fmt.Errorf({json.dumps('decode ' + wire + ' event: %w')}, err)",
            "\t\t}",
            "\t\treturn ev, nil",
        ]
    lines += [
        "\tdefault:",
        "\t\treturn UnknownEvent{Type: typ, Raw: append([]byte(nil), data...)}, nil",
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)


def _generate(out_dir: Path) -> None:
    """Write both generated files under out_dir (rooted like the repo)."""
    spec = json.loads((_REPO_ROOT / _SPEC).read_text())
    variants = _event_variants(spec)

    models_path = out_dir / _MODELS
    events_path = out_dir / _EVENTS
    models_path.parent.mkdir(parents=True, exist_ok=True)

    roots = set(_HANDWRITTEN_ROOTS) | {go for _, go in variants}
    keep = _closure(spec["components"]["schemas"], roots)
    # The union itself is reachable from nothing we keep, but say so explicitly:
    # its members are the API, and its generated form is not.
    keep.discard(_UNION)

    with tempfile.TemporaryDirectory() as tmp:
        downgraded = Path(tmp) / "spec30.json"
        spec = _downgrade(_prune(spec, keep))
        # The keyword allowlist runs before anything below adds a keyword of its
        # own, so it keeps constraining what openapi.json says and nothing else.
        _assert_supported(spec)
        variants = _rename_event_schemas(spec, variants)
        _sanitize_descriptions(spec)
        _annotate_wire_types(spec, variants)
        _skip_optional_collection_pointers(spec["components"]["schemas"])
        downgraded.write_text(json.dumps(spec))
        _run_oapi_codegen(downgraded, models_path)

    models_path.write_text(_detach_package_comment(models_path.read_text()))

    # Every variant must have landed as a Go type, or the dispatch we are about
    # to emit will not compile — catch it here with a spec-level message rather
    # than as a wall of undefined-identifier errors.
    models = models_path.read_text()
    missing = [go for _, go in variants if f"type {go} struct" not in models]
    if missing:
        raise SystemExit(
            f"{_UNION} variants absent from the generated models: "
            f"{', '.join(sorted(set(missing)))}\n"
            "Check sdks/go-client/oapi-codegen.yaml still sets `skip-prune: true` — with\n"
            "no operations left to generate, pruning would strip every schema."
        )

    events_path.write_text(_render_events(variants))


def _do_generate() -> int:
    _generate(_REPO_ROOT)
    print(f"Generated {', '.join(str(p) for p in _OUTPUTS)}")
    return 0


def _in_ci() -> bool:
    """Report whether this is a CI run, where the check may not be skipped."""
    return bool(os.environ.get("CI") or os.environ.get("GITHUB_ACTIONS"))


def _check() -> int:
    """Verify the committed bindings match openapi.json.

    Fails closed when ``oapi-codegen`` is absent, like the ``routing-pb2-fresh``
    hook's generator does for ``grpc_tools.protoc``: a check that returns 0
    because its tool is missing lets genuine drift through. A contributor with
    no Go toolchain can set ``OMNIGENT_SKIP_GO_CLIENT_CHECK=1`` to downgrade it
    to a warning; CI installs the tool and ignores that variable, so no CI
    configuration can skip the check.
    """
    if shutil.which("oapi-codegen") is None:
        if not _in_ci() and os.environ.get(_SKIP_ENV):
            print(
                f"oapi-codegen not found and {_SKIP_ENV} is set: NOT verifying the Go\n"
                "SDK bindings. Drift in them will be caught in CI, not here.",
                file=sys.stderr,
            )
            return 0
        hint = (
            ""
            if _in_ci()
            else f"\nWithout a Go toolchain, set {_SKIP_ENV}=1 to skip it locally"
            "\n(CI ignores that variable and always runs the check)."
        )
        print(
            "oapi-codegen not found, so the Go SDK bindings cannot be verified against\n"
            f"openapi.json. Install the pinned version:\n{_OAPI_CODEGEN_INSTALL}{hint}",
            file=sys.stderr,
        )
        return 1
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        _generate(tmp_dir)
        stale = [
            p
            for p in _OUTPUTS
            if not (_REPO_ROOT / p).exists()
            or not filecmp.cmp(tmp_dir / p, _REPO_ROOT / p, shallow=False)
        ]
    if stale:
        names = ", ".join(str(p) for p in stale)
        print(
            f"Go SDK bindings are out of date: {names}\n"
            f"Regenerate and commit them:\n{_REGEN_HINT}",
            file=sys.stderr,
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed bindings match openapi.json without writing",
    )
    args = parser.parse_args()
    return _check() if args.check else _do_generate()


if __name__ == "__main__":
    raise SystemExit(main())
